package uk.ac.warwick.cs261.simulation.entities.aircraft;

import org.apache.commons.math3.distribution.UniformIntegerDistribution;

/**
 * Static factory for creating {@link Aircraft} instances with randomly generated call signs.
 *
 * <p>Separate factory methods are provided for arriving and departing aircraft so that the
 * {@code isTakeoff} flag is always set correctly at the call site, eliminating the risk of
 * passing the wrong boolean directly to the {@link Aircraft} constructor.
 *
 * <p>Call signs are generated by {@link #generateCallSign()}, which combines three random
 * uppercase letters with a zero-padded four-digit number, yielding formats such as
 * {@code "ABC0042"}. Both the letter and number components are sampled independently from
 * a shared {@link UniformIntegerDistribution}, so call signs are not guaranteed to be unique
 * across a simulation run.
 *
 * <p><b>Constraints:</b>
 * <ul>
 *   <li>This class is not instantiable; all methods are static.</li>
 *   <li>The shared {@code CALL_SIGN_DISTRIBUTION} is not thread-safe; external
 *       synchronisation is required if this factory is used from multiple threads.</li>
 * </ul>
 */
public class AircraftFactory 
{
    /**
     * Shared uniform distribution over {@code [0, Integer.MAX_VALUE]} used to sample
     * both the letter and number components of generated call signs.
     */
    private static final UniformIntegerDistribution CALL_SIGN_DISTRIBUTION = new UniformIntegerDistribution(0, Integer.MAX_VALUE);

    /**
     * Creates a new departing {@link Aircraft} with a randomly generated call sign.
     *
     * @param scheduledTime the scheduled departure time, in simulation ticks
     * @param groundSpeed   the aircraft's ground speed in knots
     * @return a new {@link Aircraft} with {@code isTakeoff} set to {@code true}
     */
    public static Aircraft createTakeoffAircraft(long scheduledTime, long groundSpeed)
    {
        return new Aircraft(generateCallSign(), scheduledTime, groundSpeed, true);
    }

    /**
     * Creates a new arriving {@link Aircraft} with a randomly generated call sign.
     *
     * @param scheduledTime the scheduled arrival time, in simulation ticks
     * @param groundSpeed   the aircraft's ground speed in knots
     * @return a new {@link Aircraft} with {@code isTakeoff} set to {@code false}
     */
    public static Aircraft createLandingAircraft(long scheduledTime, long groundSpeed)
    {
        return new Aircraft(generateCallSign(), scheduledTime, groundSpeed, false);
    }

    /**
     * Generates a random call sign in the format {@code LLL0000}, where {@code L} is an
     * uppercase letter and {@code 0} is a decimal digit.
     *
     * <p>Three letters are derived from a single sample by extracting successive base-26
     * digits: {@code letter1 = sample % 26}, {@code letter2 = (sample / 26) % 26},
     * {@code letter3 = (sample / 676) % 26}. A second independent sample provides the
     * four-digit numeric suffix via {@code sample % 10000}. The result is zero-padded to
     * ensure a consistent seven-character format, e.g. {@code "ABC0042"}.
     *
     * <p>Call signs are not guaranteed to be unique across a simulation run.
     *
     * @return a randomly generated call sign string of the form {@code LLL0000}
     */
    private static String generateCallSign()
    {
        int random = CALL_SIGN_DISTRIBUTION.sample();
    
        char letter1 = (char) ('A' + (random % 26));
        char letter2 = (char) ('A' + ((random / 26) % 26));
        char letter3 = (char) ('A' + ((random / 676) % 26));

        int numbers = CALL_SIGN_DISTRIBUTION.sample() % 10000;

        return String.format("%c%c%c%04d", letter1, letter2, letter3, numbers);
    }

    /** Prevents instantiation of this static utility class. */
    private AircraftFactory() {}
}